### ISSUE TITLE
Mod names on uploaded profile not displaying correctly

### ISSUE THREAD

**Issue by PlagueHush** [Nexus-Mods/NMM-Test-Builds#11]
![mod names](https://cloud.githubusercontent.com/assets/10679343/14793456/31cebafe-0b17-11e6-94f4-a5153c28d3f4.png)

Since I edit all of my mod names (and add a three-digit number that indicates the order I installed the mod) it became apparent that mod names sent to the site are sometimes overriding the names from the mod's actual page, but they're also truncated at the first <space> in the name. The links all work though.

Other mod names haven't come from the name I gave them in NMM at all, and appear to come from the mod page. It's a very odd mix that I can't see any pattern to yet

**Comment by DuskDweller** [comment]
It should be fixed for any future profile upload, can you confirm?

**Comment by PlagueHush** [comment]
After upgrading to 0.62.5, deleting all uploaded profile, and then trying to upload the current profile to check this issue, I now can't get it to upload a profile at all. It keeps going through the archiving step, and then seems to fail without error. No profiles show up on the Nexus site, or in NMM after refreshing the uploaded profiles list

**Comment by DuskDweller** [comment]
Did you try both "backup" and "backup and share" ?

**Comment by PlagueHush** [comment]
Updated to 0.62.6. The option "backup and share current profile" under the Profile drop-down menu still throws an error 
![error 1](https://cloud.githubusercontent.com/assets/10679343/14925531/d1f876fc-0e3f-11e6-9859-725b24ad568c.png)
However, using the cloud icon on the profile tab uploaded the profile perfectly, up to the point it is suppose to open the web page to display it, at which point it shows an "Access is denied" error. Highlighting the profile and clicking the eye icon however, opens the profile fine.

And in answer to the overall question... mod names are still showing with the three digits I've set at the beginning of a custom name. For instance...
![error 2](https://cloud.githubusercontent.com/assets/10679343/14925626/388305e0-0e40-11e6-8bb9-47fc26f3725e.png)
The actual name set in NMM for the top mod in the image is "201 - Bethesda Hi-Res DLC Optimized - Unofficial High Resolution Compatibility Patch"

**Comment by PlagueHush** [comment]
The actual name set in NMM for the second mod in the list is "220 - Skyrim HD - Lite"

**Comment by DuskDweller** [comment]
This will be fixed server-side veeeery soon!

**Comment by DuskDweller** [comment]
You'll have to reupload the profile though.
