### ISSUE TITLE
NMM 0.62.14 - Online profile shows a mod missing that has a Download ID

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#94]
**Issue:**
Online profile is showing that a mod is missing even though I had manually retrieved the Download ID and Mod Info for the mod (automatic ID retrieval wasn't working for it) prior to uploading.
- Game: Skyrim
- Mod used: [Enhanced Blood Textures 3.6c](http://www.nexusmods.com/skyrim/mods/60/?)

![nmm0-62-14_profilemissingmod1](https://cloud.githubusercontent.com/assets/7691651/15375528/8ca55308-1d1d-11e6-8f89-923558a586dc.png)
![nmm0-62-14_profilemissingmod2](https://cloud.githubusercontent.com/assets/7691651/15375530/8df50d70-1d1d-11e6-8e9e-4574d1e4fae6.png)
![nmm0-62-14_profilemissingmod3](https://cloud.githubusercontent.com/assets/7691651/15375533/8f22b332-1d1d-11e6-90b3-faad90e8931b.png)

**Resolution:**
Seems that it is fixed only after I reinstall the mod. It might prove to be a problem for some other mods that has a lot of file overwrites that people rarely reinstall or remember the install order anymore.

Profiles for comparison:
- [Main Profile 0.62.14](http://www.nexusmods.com/games/profiles/10/?)
- [Main Profile 0.62.14 v2](http://www.nexusmods.com/games/profiles/120/?)

**Comment by AraFox** [comment]
Confirmed.

**Comment by DuskDweller** [comment]
Does that still happen with 0.62.15 and a new profile made with it?

**Comment by KunoMochi** [comment]
**Update:**
Reinstalled all mods on a newly created profile on 0.62.15 and uploaded the profile. Recently updated today (May 23, 2016).

[Enhanced Blood Textures 3.6c](http://www.nexusmods.com/skyrim/mods/60/?) is gone from the missing files list but now [Pretty Combat Animations 1.374](http://www.nexusmods.com/skyrim/mods/15703/?) is marked as a "Files with New Version", only it doesn't show up on the list. The mod was recently updated so I changed it over from 1.373 to 1.374 a few days ago.

Profile used: http://www.nexusmods.com/skyrim/profiles/215/

![nmm0-62-15_filenewversion1](https://cloud.githubusercontent.com/assets/7691651/15483941/7b7ff6be-2105-11e6-9369-5e6913751fb2.png)
![nmm0-62-15_filenewversion2](https://cloud.githubusercontent.com/assets/7691651/15483942/7c953db6-2105-11e6-8fd7-a85a09c268b6.png)
![nmm0-62-15_filenewversion3](https://cloud.githubusercontent.com/assets/7691651/15483946/7e0e3f76-2105-11e6-8996-be34f1cab97d.png)

**Comment by DuskDweller** [comment]
Thanks, we're trying to understand whether the issue it's NMM or server-side.

**Comment by KunoMochi** [comment]
It seems like it is either one or the other happening. lol It doesn't seem to like having both situations gone. :P

If it helps, I'll provide the local profile data from my end to look over. **Note:** I left out my other "Backup" profile from the archive so you will see 2 profiles in _ProfileManagerCfg.xml_ but one profile folder.
[ModProfiles.zip](https://github.com/Nexus-Mods/NMM-Test-Builds/files/278311/ModProfiles.zip)

Seems Github doesn't support .7z or .rar files. :(

**Comment by DuskDweller** [comment]
Don't worry, we can access it from the website :)

**Comment by DuskDweller** [comment]
Kuno can you please try updating the profile, it should work now.

**Comment by KunoMochi** [comment]
**Update 0.62.16:**
The Online Profile page now has the mod show up on the list.
![nmm0-62-16_filenewversions1](https://cloud.githubusercontent.com/assets/7691651/15519724/c774f18e-21d0-11e6-9faf-a12643c1a7fb.png)

Unfortunately, the main issue remains that it says that there is a new version of the mod available (1.374) when I, in fact, already had it downloaded and installed a few days ago installed.
